apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: bank-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: nginx
        image: nexus.local:5000/mid-bank-nginx:v0.0.1
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
